title: "Bảo-Huy's website"
description: "Academic personal website"
url: "https://baohuynguyen.github.io"
baseurl: ""

author:
  name: "Bảo-Huy Nguyễn"
  email: "huy.nguyenbao@hust.edu.vn"
  affiliation: "Hanoi University of Science and Technology / Control Technique and Innovation Lab for Electric Vehicles (CTI Lab4EV)"

markdown: kramdown
theme: null

plugins: []
